services:
  postgres:
    image: postgres:18-alpine
    container_name: cathouse-postgres
    restart: unless-stopped
    env_file:
      - .env.dev.example
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cathouse-network

  api-dev:
    build:
      context: ./cathouse-api
      dockerfile: Dockerfile.dev
    container_name: cathouse-api-dev
    restart: unless-stopped
    env_file:
      - .env.dev.example
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./cathouse-api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cathouse-network

  client-dev:
    build:
      context: ./cathouse-client
      dockerfile: Dockerfile.dev
    container_name: cathouse-client-dev
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./cathouse-client:/app
      - /app/node_modules
      - /app/.svelte-kit
    env_file:
      - .env.dev.example
    networks:
      - cathouse-network

volumes:
  postgres_data:
    driver: local

networks:
  cathouse-network:
    driver: bridge
