services:
  postgres-dev:
    image: postgres:18
    profiles: [ dev ]
    container_name: cathouse-dev-db
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data_dev:/var/lib/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d dev-db || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  api-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    profiles: [ dev ]
    container_name: cathouse-api
    env_file: 
      - .env.dev
    depends_on:
      postgres-dev:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./cathouse-api:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm install &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run start:dev"

volumes:
  postgres_data_dev: